#! /usr/bin/env bash
set -e

USB_FLASH="node_modules/.bin/particle flash --usb --yes"
SERIAL_FLASH="node_modules/.bin/particle serial flash"

if [[ -n $(lsusb -d 2b04:c006) ]]; then
    echo "Flashing Photon bootloader..."
    ${SERIAL_FLASH} bootloader-photon.bin
fi

if [[ -n $(lsusb -d 2b04:c008) ]]; then
    echo "Flashing P1 bootloader..."
    ${SERIAL_FLASH} bootloader-p1.bin
fi