version: "3.7"
services:
    compiler:
        image: brewblox/firmware-compiler:latest
        container_name: firmware-compiler
        init: true
        privileged: true
        environment:
            - MOUNTDIR=/firmware
            - MAKE_ARGS
        volumes:
            - ../:${MOUNTDIR}
        working_dir: ${MOUNTDIR}/build
        user: ${DOCKER_UID}
        command: tail -f /dev/null

    compiler-cross:
        image: brewblox/firmware-compiler:cross-latest
        container_name: firmware-compiler-cross
        init: true
        privileged: true
        environment:
            - MOUNTDIR=/firmware
            - MAKE_ARGS
        volumes:
            - ../:${MOUNTDIR}
        command: bash build-cross.sh

    simulator:
        image: brewblox/firmware-simulator:local
        privileged: true
        container_name: firmware-simulator
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            # brewblox protocol
            - "8332:8332"
            # http
            - "8380:80"

    coverage-simulator:
        image: brewblox/firmware-compiler
        container_name: firmware-coverage-simulator
        environment:
            - MOUNTDIR=/firmware
        volumes:
            - ../:${MOUNTDIR}
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        working_dir: ${MOUNTDIR}/build
        ports:
            # brewblox protocol
            - "8332:8332"
            # http
            - "8380:80"
            # websocket display emulation
            - "8380:7376"
        command: bash run-simulator.sh
